# Generated by Django 5.1.6 on 2025-03-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PemainBola',
            fields=[
                ('nama', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('domisili', models.CharField(max_length=50)),
                ('tanggalLahir', models.DateField()),
            ],
        ),
    ]
