# Generated by Django 5.1.6 on 2025-04-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_klub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemainbola',
            name='tanggalLahir',
            field=models.DateField(blank=True, null=True),
        ),
    ]
