# Generated by Django 5.1.6 on 2025-04-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_pemainbola_tanggallahir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemainbola',
            name='tanggalLahir',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
